name: "evseMQTT"
version: "latest"
slug: "evsemqtt"
description: "Home Assistant add-on for evseMQTT integration."
arch:
  - amd64
  - aarch64
url: "https://github.com/moryoav/evsemqtt-ha"
startup: "services"
boot: "auto"

image: "ghcr.io/slespersen/evsemqtt" # TODO change to this if https://github.com/slespersen/evseMQTT/pull/14 was merged
#image: "ghcr.io/b2un0/evsemqtt"

option:
  BLE_ADDRESS: "your_device_mac_address"
  BLE_PASSWORD: "your_6_digit_pin"
  UNIT: "W"
  MQTT_ENABLED: "true"
  MQTT_BROKER: "your_mqtt_broker_address"
  MQTT_PORT: 1883
  MQTT_USER: "your_mqtt_username"
  MQTT_PASSWORD: "your_mqtt_password"
  LOGGING_LEVEL: "INFO"

schema:
  BLE_ADDRESS: str
  BLE_PASSWORD: int
  UNIT: list(W|kW)
  MQTT_ENABLED: list(true|false)
  MQTT_BROKER: str
  MQTT_PORT: int
  MQTT_USER: str
  MQTT_PASSWORD: str
  LOGGING_LEVEL: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)

host_dbus: true
