name: "EVSE MQTT"
version: "latest"
slug: "evsemqtt"
description: "Home Assistant add-on for EVSE MQTT integration."
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
url: "https://github.com/moryoav/evsemqtt-ha"
startup: "services"
boot: "auto"

# Use the image without a tag, and rely on `version` above:
image: "ghcr.io/slespersen/evsemqtt"

ports:
  1883/tcp: 1883

options:
  BLE_ADDRESS: "your_device_mac_address"
  BLE_PASSWORD: "your_6_digit_pin"
  UNIT: "W"
  MQTT_ENABLED: "true"
  MQTT_BROKER: "your_mqtt_broker_address"
  MQTT_PORT: 1883
  MQTT_USER: "your_mqtt_username"
  MQTT_PASSWORD: "your_mqtt_password"
  LOGGING_LEVEL: "INFO"

schema:
  BLE_ADDRESS: str
  BLE_PASSWORD: str
  UNIT: str
  MQTT_ENABLED: str
  MQTT_BROKER: str
  MQTT_PORT: int
  MQTT_USER: str
  MQTT_PASSWORD: str
  LOGGING_LEVEL: str

# Instead of privileged: true, use full_access: true if full privileges are needed
full_access: true

# If you need DBus, consider enabling host_dbus:
# host_dbus: true
#
# And/or host_network if you need it:
# host_network: true
