name: "EVSE MQTT"
version: "latest"
slug: "evsemqtt"
description: "Home Assistant add-on for EVSE MQTT integration."
arch:
  - amd64
  - aarch64
url: "https://github.com/moryoav/evsemqtt-ha"
startup: "services"
boot: "auto"

# Use the image without a tag, and rely on `version` above:
image: "ghcr.io/slespersen/evsemqtt"

options:
  BLE_ADDRESS: "your_device_mac_address"
  BLE_PASSWORD: "your_6_digit_pin"
  UNIT: "W"
  MQTT_ENABLED: "true"
  MQTT_BROKER: "your_mqtt_broker_address"
  MQTT_PORT: 1883
  MQTT_USER: "your_mqtt_username"
  MQTT_PASSWORD: "your_mqtt_password"
  LOGGING_LEVEL: "INFO"

# Inject these options as environment variables into the container
environment:
  BLE_ADDRESS: {BLE_ADDRESS}
  BLE_PASSWORD: {BLE_PASSWORD}
  UNIT: {UNIT}
  MQTT_ENABLED: {MQTT_ENABLED}
  MQTT_BROKER: {MQTT_BROKER}
  MQTT_PORT: {MQTT_PORT}
  MQTT_USER: {MQTT_USER}
  MQTT_PASSWORD: {MQTT_PASSWORD}
  LOGGING_LEVEL: {LOGGING_LEVEL}
  
schema:
  BLE_ADDRESS: str
  BLE_PASSWORD: str
  UNIT: str
  MQTT_ENABLED: str
  MQTT_BROKER: str
  MQTT_PORT: int
  MQTT_USER: str
  MQTT_PASSWORD: str
  LOGGING_LEVEL: str

# If you need DBus, consider enabling host_dbus:
host_dbus: true
#
# And/or host_network if you need it:
# host_network: true
