name: "EVSE MQTT"
version: "latest"
slug: "evsemqtt"
description: "Home Assistant add-on for EVSE MQTT integration."
arch:
  - amd64
  - aarch64
url: "https://github.com/moryoav/evsemqtt-ha"
startup: "services"
boot: "auto"

image: "ghcr.io/slespersen/evsemqtt"

environment:
  BLE_ADDRESS: "{ble_address}"
  BLE_PASSWORD: "{ble_password}"
  UNIT: "{unit}"
  MQTT_ENABLED: "{mqtt_enabled}"
  MQTT_BROKER: "{mqtt_broker}"
  MQTT_PORT: "{mqtt_port}"
  MQTT_USER: "{mqtt_user}"
  MQTT_PASSWORD: "{mqtt_password}"
  LOGGING_LEVEL: "{logging_level}"
  
options:
  ble_address: "your_device_mac_address"
  ble_password: "your_6_digit_pin"
  unit: "W"
  mqtt_enabled: "true"
  mqtt_broker: "your_mqtt_broker_address"
  mqtt_port: 1883
  mqtt_user: "your_mqtt_username"
  mqtt_password: "your_mqtt_password"
  logging_level: "INFO"

schema:
  ble_address: str
  ble_password: str
  unit: str
  mqtt_enabled: str
  mqtt_broker: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  logging_level: str

mapoptions: true
host_dbus: true
